name:                keta
version:             0.1.0.0
github:              "githubuser/keta"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/keta#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- GLURaw
- ObjectName
- OpenGLRaw
- StateVar
- text
- transformers-0.5.2.0
- monads-tf-0.1.0.3
- SDL
library:
  source-dirs: src

executables:
  keta-exe:
    main:                main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keta

tests:
  keta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keta
