name:                keta
version:             0.1.0.0
github:              "githubuser/keta"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/keta#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- Vec
- GLURaw
- ObjectName
- OpenGLRaw
- StateVar
- text
- word8
- transformers
- monads-tf
- lens
- sdl2
- matrix
- split
- JuicyPixels
- binary
- binary-bits
- vector
- parallel
- monad-par
- monad-control
- deepseq

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - GLURaw
  - ObjectName
  - OpenGLRaw
  - StateVar
  - text
  - transformers
  - word8
  - monads-tf
  - sdl2
  - vector-space
  - codec
 
executables:
  keta-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - GLURaw
    - ObjectName
    - OpenGLRaw
    - StateVar
    - word8
    - text
    - transformers
    - monads-tf
    - sdl2
    - codec
    - keta

tests:
  keta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XRecordWildCards
    - -O2
    - -BangPatterns
    dependencies:
    - keta
